services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://62.181.53.211:3002/api
        - API_URL=http://62.181.53.211:3002/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://62.181.53.211:3002/api
      - API_URL=http://62.181.53.211:3002/api
    restart: unless-stopped
    networks:
      - seller_network

networks:
  seller_network:
    driver: bridge
